import type {
  Client,
  Professional,
  Service,
  Package,
  Appointment,
  Transaction,
  Product,
  DashboardData,
  ClientPackage,
} from "@/types";

// ==========================================
// PROFISSIONAIS
// ==========================================
export const mockProfessionals: Professional[] = [
  {
    id: "p1",
    name: "Ana Claudia Coutinho",
    email: "ana@acbeautyclinic.com.br",
    phone: "(11) 99999-0001",
    whatsapp: "(11) 99999-0001",
    role: "Esteticista Chefe",
    specialties: ["Harmonização Facial", "Limpeza de Pele", "Peeling", "Microagulhamento"],
    commissionType: "percentage",
    commissionValue: 40,
    active: true,
    color: "#ec4899",
    schedule: {
      monday: [{ start: "08:00", end: "18:00" }],
      tuesday: [{ start: "08:00", end: "18:00" }],
      wednesday: [{ start: "08:00", end: "18:00" }],
      thursday: [{ start: "08:00", end: "18:00" }],
      friday: [{ start: "08:00", end: "18:00" }],
      saturday: [{ start: "08:00", end: "13:00" }],
      sunday: [],
    },
  },
  {
    id: "p2",
    name: "Mariana Santos",
    email: "mariana@acbeautyclinic.com.br",
    phone: "(11) 99999-0002",
    whatsapp: "(11) 99999-0002",
    role: "Esteticista",
    specialties: ["Drenagem Linfática", "Massagem Modeladora", "Corpo", "Laser"],
    commissionType: "percentage",
    commissionValue: 35,
    active: true,
    color: "#8b5cf6",
    schedule: {
      monday: [{ start: "09:00", end: "19:00" }],
      tuesday: [{ start: "09:00", end: "19:00" }],
      wednesday: [{ start: "09:00", end: "19:00" }],
      thursday: [{ start: "09:00", end: "19:00" }],
      friday: [{ start: "09:00", end: "19:00" }],
      saturday: [],
      sunday: [],
    },
  },
  {
    id: "p3",
    name: "Fernanda Lima",
    email: "fernanda@acbeautyclinic.com.br",
    phone: "(11) 99999-0003",
    whatsapp: "(11) 99999-0003",
    role: "Auxiliar Estética",
    specialties: ["Depilação", "Design de Sobrancelha", "Unhas"],
    commissionType: "percentage",
    commissionValue: 30,
    active: true,
    color: "#06b6d4",
    schedule: {
      monday: [{ start: "10:00", end: "20:00" }],
      tuesday: [{ start: "10:00", end: "20:00" }],
      wednesday: [{ start: "10:00", end: "20:00" }],
      thursday: [{ start: "10:00", end: "20:00" }],
      friday: [{ start: "10:00", end: "20:00" }],
      saturday: [{ start: "09:00", end: "17:00" }],
      sunday: [],
    },
  },
];

// ==========================================
// CLIENTES
// ==========================================
export const mockClients: Client[] = [
  {
    id: "c1",
    name: "Juliana Ferreira",
    cpf: "123.456.789-01",
    rg: "12.345.678-9",
    gender: "F",
    birthDate: new Date("1990-03-15"),
    maritalStatus: "Casada",
    profession: "Professora",
    address: {
      street: "Rua das Flores",
      number: "123",
      neighborhood: "Jardim Primavera",
      city: "São Paulo",
      state: "SP",
      zipCode: "01234-567",
    },
    phone: "(11) 98765-4321",
    whatsapp: "(11) 98765-4321",
    email: "juliana.ferreira@email.com",
    instagram: "@juliana.ferreira",
    referral: "Instagram",
    registrationDate: new Date("2023-01-15"),
    status: "active",
    loyaltyPoints: 1250,
    cashbackBalance: 45.0,
    tags: ["VIP", "Pacote Ativo"],
  },
  {
    id: "c2",
    name: "Carla Mendes",
    cpf: "234.567.890-12",
    gender: "F",
    birthDate: new Date("1985-06-28"),
    maritalStatus: "Solteira",
    profession: "Médica",
    address: {
      street: "Avenida Paulista",
      number: "456",
      complement: "Apto 12",
      neighborhood: "Bela Vista",
      city: "São Paulo",
      state: "SP",
      zipCode: "01310-100",
    },
    phone: "(11) 97654-3210",
    whatsapp: "(11) 97654-3210",
    email: "carla.mendes@email.com",
    instagram: "@carla.mendes.md",
    referral: "Indicação de amiga",
    registrationDate: new Date("2023-03-20"),
    status: "active",
    loyaltyPoints: 890,
    cashbackBalance: 30.0,
    tags: ["Regular"],
  },
  {
    id: "c3",
    name: "Beatriz Costa",
    cpf: "345.678.901-23",
    gender: "F",
    birthDate: new Date("1995-12-10"),
    maritalStatus: "Solteira",
    profession: "Advogada",
    address: {
      street: "Rua Consolação",
      number: "789",
      neighborhood: "Consolação",
      city: "São Paulo",
      state: "SP",
      zipCode: "01302-000",
    },
    phone: "(11) 96543-2109",
    whatsapp: "(11) 96543-2109",
    email: "beatriz.costa@email.com",
    referral: "Google",
    registrationDate: new Date("2023-06-10"),
    status: "active",
    loyaltyPoints: 420,
    cashbackBalance: 15.0,
  },
  {
    id: "c4",
    name: "Patrícia Oliveira",
    cpf: "456.789.012-34",
    gender: "F",
    birthDate: new Date("1988-09-22"),
    profession: "Empresária",
    address: {
      street: "Rua Oscar Freire",
      number: "321",
      neighborhood: "Jardins",
      city: "São Paulo",
      state: "SP",
      zipCode: "01426-001",
    },
    phone: "(11) 95432-1098",
    whatsapp: "(11) 95432-1098",
    email: "patricia.oliveira@empresa.com.br",
    instagram: "@patriciaoliveiraoficial",
    referral: "Indicação",
    registrationDate: new Date("2022-11-05"),
    status: "active",
    loyaltyPoints: 3200,
    cashbackBalance: 120.0,
    tags: ["VIP", "Top Cliente"],
  },
  {
    id: "c5",
    name: "Renata Silva",
    cpf: "567.890.123-45",
    gender: "F",
    birthDate: new Date("1992-04-05"),
    profession: "Designer",
    address: {
      street: "Rua Augusta",
      number: "654",
      neighborhood: "Consolação",
      city: "São Paulo",
      state: "SP",
      zipCode: "01305-100",
    },
    phone: "(11) 94321-0987",
    whatsapp: "(11) 94321-0987",
    email: "renata.silva@email.com",
    referral: "Instagram",
    registrationDate: new Date("2024-01-08"),
    status: "active",
    loyaltyPoints: 150,
    cashbackBalance: 5.0,
    tags: ["Novo"],
  },
  {
    id: "c6",
    name: "Amanda Rocha",
    cpf: "678.901.234-56",
    gender: "F",
    birthDate: new Date("1987-07-18"),
    profession: "Enfermeira",
    address: {
      street: "Rua da Liberdade",
      number: "987",
      neighborhood: "Liberdade",
      city: "São Paulo",
      state: "SP",
      zipCode: "01503-000",
    },
    phone: "(11) 93210-9876",
    whatsapp: "(11) 93210-9876",
    registrationDate: new Date("2023-09-14"),
    status: "inactive",
    loyaltyPoints: 680,
    cashbackBalance: 25.0,
    tags: ["Inativo"],
  },
];

// ==========================================
// SERVIÇOS
// ==========================================
export const mockServices: Service[] = [
  {
    id: "s1",
    name: "Limpeza de Pele Profunda",
    category: "Tratamento Facial",
    description: "Limpeza profunda com extração, máscara e hidratação",
    duration: 90,
    price: 180.0,
    commission: 35,
    professionalIds: ["p1", "p2"],
    active: true,
    color: "#ec4899",
  },
  {
    id: "s2",
    name: "Peeling Químico",
    category: "Tratamento Facial",
    description: "Peeling com ácidos para renovação celular",
    duration: 60,
    price: 220.0,
    commission: 35,
    professionalIds: ["p1"],
    active: true,
    color: "#8b5cf6",
  },
  {
    id: "s3",
    name: "Microagulhamento",
    category: "Tratamento Facial",
    description: "Microagulhamento com vitaminas e ácido hialurônico",
    duration: 90,
    price: 380.0,
    commission: 40,
    professionalIds: ["p1"],
    active: true,
    color: "#f59e0b",
  },
  {
    id: "s4",
    name: "Drenagem Linfática",
    category: "Tratamento Corporal",
    description: "Drenagem manual com 60 movimentos",
    duration: 60,
    price: 150.0,
    commission: 30,
    professionalIds: ["p2"],
    active: true,
    color: "#06b6d4",
  },
  {
    id: "s5",
    name: "Massagem Modeladora",
    category: "Tratamento Corporal",
    description: "Massagem para modelar o corpo e reduzir medidas",
    duration: 60,
    price: 160.0,
    commission: 30,
    professionalIds: ["p2"],
    active: true,
    color: "#10b981",
  },
  {
    id: "s6",
    name: "Harmonização Facial",
    category: "Procedimentos Especiais",
    description: "Harmonização com ácido hialurônico e botox",
    duration: 120,
    price: 1200.0,
    commission: 40,
    professionalIds: ["p1"],
    active: true,
    color: "#ef4444",
  },
  {
    id: "s7",
    name: "Depilação a Laser",
    category: "Depilação",
    description: "Depilação definitiva a laser IPL",
    duration: 45,
    price: 280.0,
    commission: 30,
    professionalIds: ["p2", "p3"],
    active: true,
    color: "#6366f1",
  },
  {
    id: "s8",
    name: "Design de Sobrancelha",
    category: "Estética",
    description: "Design com linha e tintura",
    duration: 30,
    price: 60.0,
    commission: 35,
    professionalIds: ["p3"],
    active: true,
    color: "#84cc16",
  },
];

// ==========================================
// PACOTES
// ==========================================
export const mockPackages: Package[] = [
  {
    id: "pkg1",
    name: "Pacote Renovação Facial",
    description: "5 sessões de limpeza de pele + 3 peelings",
    sessions: 8,
    validityDays: 120,
    services: [
      { serviceId: "s1", serviceName: "Limpeza de Pele Profunda", sessions: 5 },
      { serviceId: "s2", serviceName: "Peeling Químico", sessions: 3 },
    ],
    discount: 15,
    price: 1190.0,
    maxInstallments: 6,
    active: true,
  },
  {
    id: "pkg2",
    name: "Pacote Corpo Definido",
    description: "10 sessões de drenagem + 10 massagens modeladoras",
    sessions: 20,
    validityDays: 90,
    services: [
      { serviceId: "s4", serviceName: "Drenagem Linfática", sessions: 10 },
      { serviceId: "s5", serviceName: "Massagem Modeladora", sessions: 10 },
    ],
    discount: 20,
    price: 2480.0,
    maxInstallments: 12,
    active: true,
  },
  {
    id: "pkg3",
    name: "Pacote Microagulhamento Premium",
    description: "4 sessões de microagulhamento facial",
    sessions: 4,
    validityDays: 150,
    services: [
      { serviceId: "s3", serviceName: "Microagulhamento", sessions: 4 },
    ],
    discount: 10,
    price: 1368.0,
    maxInstallments: 6,
    active: true,
  },
  {
    id: "pkg4",
    name: "Pacote Depilação Total",
    description: "6 sessões de depilação a laser (área escolhida)",
    sessions: 6,
    validityDays: 180,
    services: [
      { serviceId: "s7", serviceName: "Depilação a Laser", sessions: 6 },
    ],
    discount: 20,
    price: 1344.0,
    maxInstallments: 12,
    active: true,
  },
];

// ==========================================
// AGENDAMENTOS
// ==========================================
const today = new Date();
const todayStr = today.toISOString().split("T")[0];

export const mockAppointments: Appointment[] = [
  {
    id: "a1",
    clientId: "c1",
    clientName: "Juliana Ferreira",
    clientPhone: "(11) 98765-4321",
    professionalId: "p1",
    professionalName: "Ana Claudia Coutinho",
    serviceId: "s1",
    serviceName: "Limpeza de Pele Profunda",
    date: new Date(`${todayStr}T09:00:00`),
    startTime: "09:00",
    endTime: "10:30",
    status: "confirmed",
    color: "#ec4899",
    reminderSent: true,
    confirmationSent: true,
    notes: "Cliente prefere produtos sem fragrância",
  },
  {
    id: "a2",
    clientId: "c2",
    clientName: "Carla Mendes",
    clientPhone: "(11) 97654-3210",
    professionalId: "p1",
    professionalName: "Ana Claudia Coutinho",
    serviceId: "s3",
    serviceName: "Microagulhamento",
    date: new Date(`${todayStr}T11:00:00`),
    startTime: "11:00",
    endTime: "12:30",
    status: "in_progress",
    color: "#f59e0b",
    reminderSent: true,
    confirmationSent: true,
  },
  {
    id: "a3",
    clientId: "c4",
    clientName: "Patrícia Oliveira",
    clientPhone: "(11) 95432-1098",
    professionalId: "p2",
    professionalName: "Mariana Santos",
    serviceId: "s4",
    serviceName: "Drenagem Linfática",
    date: new Date(`${todayStr}T09:30:00`),
    startTime: "09:30",
    endTime: "10:30",
    status: "completed",
    color: "#06b6d4",
    reminderSent: true,
    confirmationSent: true,
  },
  {
    id: "a4",
    clientId: "c3",
    clientName: "Beatriz Costa",
    clientPhone: "(11) 96543-2109",
    professionalId: "p1",
    professionalName: "Ana Claudia Coutinho",
    serviceId: "s2",
    serviceName: "Peeling Químico",
    date: new Date(`${todayStr}T14:00:00`),
    startTime: "14:00",
    endTime: "15:00",
    status: "scheduled",
    color: "#8b5cf6",
    reminderSent: false,
    confirmationSent: false,
  },
  {
    id: "a5",
    clientId: "c5",
    clientName: "Renata Silva",
    clientPhone: "(11) 94321-0987",
    professionalId: "p3",
    professionalName: "Fernanda Lima",
    serviceId: "s8",
    serviceName: "Design de Sobrancelha",
    date: new Date(`${todayStr}T15:30:00`),
    startTime: "15:30",
    endTime: "16:00",
    status: "scheduled",
    color: "#84cc16",
    reminderSent: false,
    confirmationSent: false,
  },
  {
    id: "a6",
    clientId: "c1",
    clientName: "Juliana Ferreira",
    clientPhone: "(11) 98765-4321",
    professionalId: "p2",
    professionalName: "Mariana Santos",
    serviceId: "s5",
    serviceName: "Massagem Modeladora",
    date: new Date(`${todayStr}T16:30:00`),
    startTime: "16:30",
    endTime: "17:30",
    status: "scheduled",
    color: "#10b981",
    reminderSent: false,
    confirmationSent: false,
  },
];

// ==========================================
// TRANSAÇÕES FINANCEIRAS
// ==========================================
export const mockTransactions: Transaction[] = [
  {
    id: "t1",
    type: "income",
    category: "Serviços",
    description: "Limpeza de Pele - Juliana Ferreira",
    clientId: "c1",
    amount: 180.0,
    dueDate: new Date(),
    paymentDate: new Date(),
    status: "paid",
    paymentMethod: "pix",
  },
  {
    id: "t2",
    type: "income",
    category: "Pacotes",
    description: "Pacote Renovação Facial - Carla Mendes",
    clientId: "c2",
    amount: 1190.0,
    dueDate: new Date(),
    paymentDate: new Date(),
    status: "paid",
    paymentMethod: "credit_card",
    installments: 6,
  },
  {
    id: "t3",
    type: "expense",
    category: "Fornecedor",
    description: "Compra de produtos estéticos - Cosmetic Plus",
    amount: 850.0,
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    status: "pending",
  },
  {
    id: "t4",
    type: "income",
    category: "Serviços",
    description: "Microagulhamento - Patrícia Oliveira",
    clientId: "c4",
    amount: 380.0,
    dueDate: new Date(),
    paymentDate: new Date(),
    status: "paid",
    paymentMethod: "pix",
  },
  {
    id: "t5",
    type: "expense",
    category: "Aluguel",
    description: "Aluguel da clínica - Julho/2025",
    amount: 3500.0,
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    status: "pending",
  },
  {
    id: "t6",
    type: "expense",
    category: "Salários",
    description: "Pagamento Mariana Santos - Junho/2025",
    amount: 2800.0,
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    status: "overdue",
  },
  {
    id: "t7",
    type: "income",
    category: "Serviços",
    description: "Harmonização Facial - Beatriz Costa",
    clientId: "c3",
    amount: 1200.0,
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    status: "pending",
  },
  {
    id: "t8",
    type: "income",
    category: "Serviços",
    description: "Drenagem Linfática - Renata Silva",
    clientId: "c5",
    amount: 150.0,
    dueDate: new Date(),
    paymentDate: new Date(),
    status: "paid",
    paymentMethod: "cash",
  },
];

// ==========================================
// PRODUTOS / ESTOQUE
// ==========================================
export const mockProducts: Product[] = [
  {
    id: "prod1",
    name: "Ácido Hialurônico 2%",
    category: "cosmetic",
    description: "Soro hidratante com ácido hialurônico puro",
    unitPrice: 45.0,
    quantity: 12,
    minQuantity: 5,
    unit: "unidade",
    active: true,
  },
  {
    id: "prod2",
    name: "Peeling Mandélico 30%",
    category: "cosmetic",
    description: "Peeling com ácido mandélico para renovação celular",
    unitPrice: 85.0,
    quantity: 3,
    minQuantity: 5,
    unit: "frasco",
    active: true,
  },
  {
    id: "prod3",
    name: "Luvas Descartáveis P",
    category: "disposable",
    quantity: 200,
    minQuantity: 100,
    unit: "pares",
    unitPrice: 0.35,
    active: true,
  },
  {
    id: "prod4",
    name: "Máscara Cirúrgica",
    category: "disposable",
    quantity: 150,
    minQuantity: 50,
    unit: "unidade",
    unitPrice: 0.80,
    active: true,
  },
  {
    id: "prod5",
    name: "Vitamina C 20%",
    category: "cosmetic",
    description: "Sérum vitamina C para clareamento e antioxidante",
    unitPrice: 62.0,
    quantity: 8,
    minQuantity: 5,
    unit: "frasco",
    active: true,
  },
  {
    id: "prod6",
    name: "Agulhas Microagulhamento 1.0mm",
    category: "material",
    quantity: 25,
    minQuantity: 10,
    unit: "unidade",
    unitPrice: 15.0,
    active: true,
  },
];

// ==========================================
// PACOTES DE CLIENTES
// ==========================================
export const mockClientPackages: ClientPackage[] = [
  {
    id: "cp1",
    clientId: "c1",
    packageId: "pkg1",
    packageName: "Pacote Renovação Facial",
    totalSessions: 8,
    completedSessions: 3,
    remainingSessions: 5,
    canceledSessions: 0,
    missedSessions: 0,
    purchaseDate: new Date("2025-04-15"),
    expirationDate: new Date("2025-08-15"),
    status: "active",
    totalValue: 1190.0,
    paidValue: 1190.0,
    sessions: [],
  },
  {
    id: "cp2",
    clientId: "c4",
    packageId: "pkg2",
    packageName: "Pacote Corpo Definido",
    totalSessions: 20,
    completedSessions: 18,
    remainingSessions: 2,
    canceledSessions: 0,
    missedSessions: 1,
    purchaseDate: new Date("2025-03-01"),
    expirationDate: new Date("2025-06-30"),
    status: "active",
    totalValue: 2480.0,
    paidValue: 2480.0,
    sessions: [],
  },
  {
    id: "cp3",
    clientId: "c2",
    packageId: "pkg3",
    packageName: "Pacote Microagulhamento Premium",
    totalSessions: 4,
    completedSessions: 1,
    remainingSessions: 3,
    canceledSessions: 0,
    missedSessions: 0,
    purchaseDate: new Date("2025-06-01"),
    expirationDate: new Date("2025-11-01"),
    status: "active",
    totalValue: 1368.0,
    paidValue: 1368.0,
    sessions: [],
  },
];

// ==========================================
// DASHBOARD DATA
// ==========================================
export const mockDashboardData: DashboardData = {
  financial: {
    dailyRevenue: 2110.0,
    weeklyRevenue: 12450.0,
    monthlyRevenue: 48320.0,
    yearlyRevenue: 524800.0,
    profit: 28992.0,
    expenses: 19328.0,
    accountsPayable: 7850.0,
    overduePayable: 2800.0,
    accountsReceivable: 3280.0,
    cashFlow: 28992.0,
    averageTicket: 285.0,
  },
  clients: {
    total: 284,
    active: 231,
    inactive: 53,
    newThisMonth: 18,
    recurring: 143,
    returnRate: 73.5,
    birthdays: mockClients.filter((c) => {
      const today = new Date();
      const birth = new Date(c.birthDate);
      return birth.getMonth() === today.getMonth();
    }),
  },
  appointments: {
    today: 6,
    upcoming: mockAppointments.filter((a) => a.status === "scheduled"),
    inProgress: 1,
    absenceRate: 8.2,
    cancellations: 3,
    completed: 3,
  },
  services: {
    topSelling: [
      { id: "s1", name: "Limpeza de Pele", count: 87, revenue: 15660 },
      { id: "s4", name: "Drenagem Linfática", count: 72, revenue: 10800 },
      { id: "s3", name: "Microagulhamento", count: 45, revenue: 17100 },
      { id: "s2", name: "Peeling Químico", count: 38, revenue: 8360 },
      { id: "s7", name: "Depilação a Laser", count: 31, revenue: 8680 },
    ],
    mostProfitable: [
      { id: "s6", name: "Harmonização Facial", count: 12, revenue: 14400 },
      { id: "s3", name: "Microagulhamento", count: 45, revenue: 17100 },
      { id: "pkg2", name: "Pacote Corpo Definido", count: 8, revenue: 19840 },
    ],
    mostUsedProducts: [
      { id: "prod1", name: "Ácido Hialurônico 2%", count: 45 },
      { id: "prod3", name: "Luvas Descartáveis", count: 312 },
      { id: "prod5", name: "Vitamina C 20%", count: 38 },
    ],
    packagesExpiring: mockClientPackages.filter((p) => {
      const daysLeft = Math.ceil(
        (new Date(p.expirationDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24)
      );
      return daysLeft <= 30 && daysLeft > 0;
    }),
  },
  professionals: {
    ranking: [
      {
        professionalId: "p1",
        professionalName: "Ana Claudia Coutinho",
        appointments: 89,
        revenue: 28560,
        commission: 11424,
      },
      {
        professionalId: "p2",
        professionalName: "Mariana Santos",
        appointments: 76,
        revenue: 18320,
        commission: 6412,
      },
      {
        professionalId: "p3",
        professionalName: "Fernanda Lima",
        appointments: 54,
        revenue: 8640,
        commission: 3024,
      },
    ],
  },
};

// ==========================================
// CHART DATA
// ==========================================
export const monthlyRevenueData = [
  { month: "Jan", receita: 38200, despesas: 16400, lucro: 21800 },
  { month: "Fev", receita: 42100, despesas: 17200, lucro: 24900 },
  { month: "Mar", receita: 39800, despesas: 15800, lucro: 24000 },
  { month: "Abr", receita: 45600, despesas: 18200, lucro: 27400 },
  { month: "Mai", receita: 51200, despesas: 19800, lucro: 31400 },
  { month: "Jun", receita: 48320, despesas: 19328, lucro: 28992 },
];

export const weeklyAppointmentsData = [
  { day: "Seg", confirmados: 8, realizados: 7, faltas: 1 },
  { day: "Ter", confirmados: 10, realizados: 9, faltas: 1 },
  { day: "Qua", confirmados: 9, realizados: 8, faltas: 1 },
  { day: "Qui", confirmados: 11, realizados: 10, faltas: 0 },
  { day: "Sex", confirmados: 12, realizados: 11, faltas: 1 },
  { day: "Sáb", confirmados: 7, realizados: 6, faltas: 0 },
];

export const clientGrowthData = [
  { month: "Jan", novos: 12, recorrentes: 95, total: 240 },
  { month: "Fev", novos: 15, recorrentes: 102, total: 252 },
  { month: "Mar", novos: 11, recorrentes: 108, total: 261 },
  { month: "Abr", novos: 18, recorrentes: 115, total: 273 },
  { month: "Mai", novos: 14, recorrentes: 121, total: 279 },
  { month: "Jun", novos: 18, recorrentes: 128, total: 284 },
];

export const serviceDistributionData = [
  { name: "Facial", value: 42, color: "#ec4899" },
  { name: "Corporal", value: 28, color: "#8b5cf6" },
  { name: "Depilação", value: 16, color: "#06b6d4" },
  { name: "Especiais", value: 10, color: "#f59e0b" },
  { name: "Estética", value: 4, color: "#10b981" },
];

export const paymentMethodData = [
  { name: "PIX", value: 38, color: "#22c55e" },
  { name: "Cartão Crédito", value: 32, color: "#3b82f6" },
  { name: "Cartão Débito", value: 15, color: "#6366f1" },
  { name: "Dinheiro", value: 10, color: "#f59e0b" },
  { name: "Outros", value: 5, color: "#94a3b8" },
];
